const deck = {
  SA: {
    code: "AS",
    image: require("@/deck/images/AS.png"),
    value: "ACE",
    blackjack: 11,
    suit: "SPADES",
  },
  S2: {
    code: "2S",
    image: require("@/deck/images/2S.png"),
    value: "2",
    blackjack: 2,
    suit: "SPADES",
  },
  S3: {
    code: "3S",
    image: require("@/deck/images/3S.png"),
    value: "3",
    blackjack: 3,
    suit: "SPADES",
  },
  S4: {
    code: "4S",
    image: require("@/deck/images/4S.png"),
    value: "4",
    blackjack: 4,
    suit: "SPADES",
  },
  S5: {
    code: "5S",
    image: require("@/deck/images/5S.png"),
    value: "5",
    blackjack: 5,
    suit: "SPADES",
  },
  S6: {
    code: "6S",
    image: require("@/deck/images/6S.png"),
    value: "6",
    blackjack: 6,
    suit: "SPADES",
  },
  S7: {
    code: "7S",
    image: require("@/deck/images/7S.png"),
    value: "7",
    blackjack: 7,
    suit: "SPADES",
  },
  S8: {
    code: "8S",
    image: require("@/deck/images/8S.png"),
    value: "8",
    blackjack: 8,
    suit: "SPADES",
  },
  S9: {
    code: "9S",
    image: require("@/deck/images/9S.png"),
    value: "9",
    blackjack: 9,
    suit: "SPADES",
  },
  S0: {
    code: "0S",
    image: require("@/deck/images/0S.png"),
    value: "10",
    blackjack: 10,
    suit: "SPADES",
  },
  SJ: {
    code: "JS",
    image: require("@/deck/images/JS.png"),
    value: "JACK",
    blackjack: 10,
    suit: "SPADES",
  },
  SQ: {
    code: "QS",
    image: require("@/deck/images/QS.png"),
    value: "JACK",
    blackjack: 10,
    suit: "SPADES",
  },
  SK: {
    code: "KS",
    image: require("@/deck/images/KS.png"),
    value: "JACK",
    blackjack: 10,
    suit: "SPADES",
  },
  DA: {
    code: "AD",
    image: require("@/deck/images/AD.png"),
    value: "ACE",
    blackjack: 11,
    suit: "DIAMONDS",
  },
  D2: {
    code: "2D",
    image: require("@/deck/images/2D.png"),
    value: "2",
    blackjack: 2,
    suit: "DIAMONDS",
  },
  D3: {
    code: "3D",
    image: require("@/deck/images/3D.png"),
    value: "3",
    blackjack: 3,
    suit: "DIAMONDS",
  },
  D4: {
    code: "4D",
    image: require("@/deck/images/4D.png"),
    value: "4",
    blackjack: 4,
    suit: "DIAMONDS",
  },
  D5: {
    code: "5D",
    image: require("@/deck/images/5D.png"),
    value: "5",
    blackjack: 5,
    suit: "DIAMONDS",
  },
  D6: {
    code: "6D",
    image: require("@/deck/images/6D.png"),
    value: "6",
    blackjack: 6,
    suit: "DIAMONDS",
  },
  D7: {
    code: "7D",
    image: require("@/deck/images/7D.png"),
    value: "7",
    blackjack: 7,
    suit: "DIAMONDS",
  },
  D8: {
    code: "8D",
    image: require("@/deck/images/8D.png"),
    value: "8",
    blackjack: 8,
    suit: "DIAMONDS",
  },
  D9: {
    code: "9D",
    image: require("@/deck/images/9D.png"),
    value: "9",
    blackjack: 9,
    suit: "DIAMONDS",
  },
  D0: {
    code: "0D",
    image: require("@/deck/images/0D.png"),
    value: "10",
    blackjack: 10,
    suit: "DIAMONDS",
  },
  DJ: {
    code: "JD",
    image: require("@/deck/images/JD.png"),
    value: "JACK",
    blackjack: 10,
    suit: "DIAMONDS",
  },
  DQ: {
    code: "QD",
    image: require("@/deck/images/QD.png"),
    value: "QUEEN",
    blackjack: 10,
    suit: "DIAMONDS",
  },
  DK: {
    code: "KD",
    image: require("@/deck/images/KD.png"),
    value: "KING",
    blackjack: 10,
    suit: "DIAMONDS",
  },
  CA: {
    code: "AC",
    image: require("@/deck/images/AC.png"),
    value: "ACE",
    blackjack: 11,
    suit: "CLUBS",
  },
  C2: {
    code: "2C",
    image: require("@/deck/images/2C.png"),
    value: "2",
    blackjack: 2,
    suit: "CLUBS",
  },
  C3: {
    code: "3C",
    image: require("@/deck/images/3C.png"),
    value: "3",
    blackjack: 3,
    suit: "CLUBS",
  },
  C4: {
    code: "4C",
    image: require("@/deck/images/4C.png"),
    value: "4",
    blackjack: 4,
    suit: "CLUBS",
  },
  C5: {
    code: "5C",
    image: require("@/deck/images/5C.png"),
    value: "5",
    blackjack: 5,
    suit: "CLUBS",
  },
  C6: {
    code: "6C",
    image: require("@/deck/images/6C.png"),
    value: "6",
    blackjack: 6,
    suit: "CLUBS",
  },
  C7: {
    code: "7C",
    image: require("@/deck/images/7C.png"),
    value: "7",
    blackjack: 7,
    suit: "CLUBS",
  },
  C8: {
    code: "8C",
    image: require("@/deck/images/8C.png"),
    value: "8",
    blackjack: 8,
    suit: "CLUBS",
  },
  C9: {
    code: "9C",
    image: require("@/deck/images/9C.png"),
    value: "9",
    blackjack: 9,
    suit: "CLUBS",
  },
  C0: {
    code: "0C",
    image: require("@/deck/images/0C.png"),
    value: "10",
    blackjack: 10,
    suit: "CLUBS",
  },
  CJ: {
    code: "JC",
    image: require("@/deck/images/JC.png"),
    value: "JACK",
    blackjack: 10,
    suit: "CLUBS",
  },
  CQ: {
    code: "QC",
    image: require("@/deck/images/QC.png"),
    value: "QUEEN",
    blackjack: 10,
    suit: "CLUBS",
  },
  CK: {
    code: "KC",
    image: require("@/deck/images/KC.png"),
    value: "KING",
    blackjack: 10,
    suit: "CLUBS",
  },
  HA: {
    code: "AH",
    image: require("@/deck/images/AH.png"),
    value: "ACE",
    blackjack: 1 || 11,
    suit: "HEARTS",
  },
  H2: {
    code: "2H",
    image: require("@/deck/images/2H.png"),
    value: "2",
    blackjack: 2,
    suit: "HEARTS",
  },
  H3: {
    code: "3H",
    image: require("@/deck/images/3H.png"),
    value: "3",
    blackjack: 3,
    suit: "HEARTS",
  },
  H4: {
    code: "4H",
    image: require("@/deck/images/4H.png"),
    value: "4",
    blackjack: 4,
    suit: "HEARTS",
  },
  H5: {
    code: "5H",
    image: require("@/deck/images/5H.png"),
    value: "5",
    blackjack: 5,
    suit: "HEARTS",
  },
  H6: {
    code: "6H",
    image: require("@/deck/images/6H.png"),
    value: "6",
    blackjack: 6,
    suit: "HEARTS",
  },
  H7: {
    code: "7H",
    image: require("@/deck/images/7H.png"),
    value: "7",
    blackjack: 7,
    suit: "HEARTS",
  },
  H8: {
    code: "8H",
    image: require("@/deck/images/8H.png"),
    value: "8",
    blackjack: 8,
    suit: "HEARTS",
  },
  H9: {
    code: "9H",
    image: require("@/deck/images/9H.png"),
    value: "9",
    blackjack: 9,
    suit: "HEARTS",
  },
  H0: {
    code: "0H",
    image: require("@/deck/images/0H.png"),
    value: "10",
    blackjack: 10,
    suit: "HEARTS",
  },
  HJ: {
    code: "JH",
    image: require("@/deck/images/JH.png"),
    value: "JACK",
    blackjack: 10,
    suit: "HEARTS",
  },
  HQ: {
    code: "QH",
    image: require("@/deck/images/QH.png"),
    value: "QUEEN",
    blackjack: 10,
    suit: "HEARTS",
  },
  HK: {
    code: "KH",
    image: require("@/deck/images/KH.png"),
    value: "KING",
    blackjack: 10,
    suit: "HEARTS",
  },
};
export { deck };
